name: aplikasilaundry
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: any
  firebase_auth: any
  google_sign_in: ^6.2.1
  cloud_firestore: any
  url_launcher: ^6.2.5
  http: ^1.6.0
  image_picker: ^1.2.2
  firebase_storage: ^13.3.0
  intl: ^0.20.2
  audioplayers: ^6.6.0
  printing: ^5.14.3
  pdf: ^3.12.0
  fl_chart: ^1.2.0
  shared_preferences: ^2.5.5
  firebase_messaging: ^16.4.1
  firebase_database: ^12.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/logolaundry.png
    - assets/welcome.png
    - assets/splash_illustration.png
    - assets/onboarding_1.png
    - assets/onboarding_2.png
    - assets/onboarding_3.png
    - assets/welcome_hero.png
    - assets/machine_card_icon.png
    - assets/notification.mp3
    - assets/app_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"