// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSZ4CEI259wLP7wbAdFFDELWIsRkeoyTg',
    appId: '1:996988566077:web:8666b13eab896c24954854',
    messagingSenderId: '996988566077',
    projectId: 'monitoringlaundry-adba4',
    authDomain: 'monitoringlaundry-adba4.firebaseapp.com',
    storageBucket: 'monitoringlaundry-adba4.firebasestorage.app',
    measurementId: 'G-LCM75KHLSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEu9nuMeqjh_rQ5q-_XoH1LniJwPK8P6U',
    appId: '1:996988566077:android:e3389cb733bd429b954854',
    messagingSenderId: '996988566077',
    projectId: 'monitoringlaundry-adba4',
    storageBucket: 'monitoringlaundry-adba4.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4yfOQAknbb5ROrWCSaynlvnL9xNP869Y',
    appId: '1:996988566077:ios:6f79a029ff6009d7954854',
    messagingSenderId: '996988566077',
    projectId: 'monitoringlaundry-adba4',
    storageBucket: 'monitoringlaundry-adba4.firebasestorage.app',
    iosBundleId: 'com.example.aplikasilaundry',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4yfOQAknbb5ROrWCSaynlvnL9xNP869Y',
    appId: '1:996988566077:ios:6f79a029ff6009d7954854',
    messagingSenderId: '996988566077',
    projectId: 'monitoringlaundry-adba4',
    storageBucket: 'monitoringlaundry-adba4.firebasestorage.app',
    iosBundleId: 'com.example.aplikasilaundry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSZ4CEI259wLP7wbAdFFDELWIsRkeoyTg',
    appId: '1:996988566077:web:a9422fc4cb51d42d954854',
    messagingSenderId: '996988566077',
    projectId: 'monitoringlaundry-adba4',
    authDomain: 'monitoringlaundry-adba4.firebaseapp.com',
    storageBucket: 'monitoringlaundry-adba4.firebasestorage.app',
    measurementId: 'G-10YYL1HWF3',
  );
}
